name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Gradle build and test
    - name: Build & Test with Gradle
      if: exists('./gradlew')
      run: |
        ./gradlew build
        ./gradlew test

    # Maven build and test
    - name: Build & Test with Maven
      if: exists('pom.xml')
      run: |
        mvn clean install
        mvn test